### ISSUE TITLE
Warning: gmp_init(): Unable to convert variable to GMP - wrong type

### ISSUE THREAD

**Issue by josecelano** [mdanter/phpecc#90] opened 2015-06-23 16:50 UTC
I get this error: 

```shell
Warning: gmp_init(): Unable to convert variable to GMP - wrong type in C:\Users\Jose\Projects\BlockCypher\php-client\vendor\mdanter\ecc\src\Math\Gmp.php on line 281
```
in [Gmp::baseConvert($number, $from, $to)](https://github.com/mdanter/phpecc/blob/8b588fc094ba743d8f8c84980bcc6b470c4baed7/src/Math/Gmp.php#L281)

with this values:

```
Number:
double(4294967295)
From:
int(10)
To:
int(2)
```

**Comment by aztech-dev** [comment] 2015-06-23 22:33
Can you give a bit more context (ie, a backtrace, sample calling code) ? It's hard to reproduce your issue as the code you mention is used a lot in the library.

**Comment by josecelano** [comment] 2015-06-24 07:49
You can reproduce the problem witn:

```php
<?php
gmp_init((double)123456, 10);
```

or

```php
<?php
gmp_init((float)123456, 10);
```

You can run that sample on http://phptester.net/ and you will get this warning:

```
WARNING gmp_init() [function.gmp-init]: Unable to convert variable to GMP - wrong type on line number 3
```

The problem is gmp_init expects an integer value.

I am not using this library directly. I am using this one: 
https://github.com/Bit-Wasp/bitcoin-php

And it calls this library here:
https://github.com/Bit-Wasp/buffertools-php/blob/master/src/Buffertools/Types/AbstractUint.php#L29

**Comment by aztech-dev** [comment] 2015-06-24 07:56
Allright, the issue is that GMP only accepts string or integers. You should probably cast your value to a string before calling the method you use in buffer-tools to avoid the error. Not sure this relates to php-ecc directly...

**Comment by btcdrak** [comment] 2015-06-24 08:15
@afk11 Problem is [that particular API](https://github.com/Bit-Wasp/buffertools-php/blob/master/src/Buffertools/Types/AbstractUint.php#L29) is expecting an integer so we might be wise to add a type check there and throw an InvalidArgumentException.

**Comment by afk11** [comment] 2015-06-25 02:17
I think you're running into phpisms - tldr: pass it as a string and it should work fine. 

4294967295 is apparently large enough (it's 2^32-1) for PHP to trigger conversion from an int to a double, which Gmp won't handle. Assuming you're on a 32bit machine? Gmp will accept int's, but PHP doesn't have arbitrary sized integers, they're limited by machine register size, so unfortunately strings are the way to go with big integer math. 

I'd say we can close this issue without action on phpecc.. gmp_init() and gmp_strval() are called everywhere to ensure consistency and to keep things simple. It's due to this I'd be against excessive statements in the math library anyways.

**Comment by aztech-dev** [comment] 2015-06-25 14:10
Same here, I'm fairly against adding extra type checks in the math classes of php-ecc considering the negative performance impact it would have (and performance is already bad enough).

**Comment by josecelano** [comment] 2015-06-25 14:32
ok thanks. Then I suppose a cast should be added here:

https://github.com/mdanter/phpecc/blob/master/src/Math/Gmp.php#L281

**Comment by afk11** [comment] 2015-06-25 17:03
Could you instead submit a PR to bitcoin-php to always cast a TransactionOutput value to a string? The one off cost is best placed there, rather casting in Gmp, which might suppress errors a user would like to know about?

**Comment by josecelano** [comment] 2015-06-25 17:11
I have also opened an issue there:

https://github.com/Bit-Wasp/bitcoin-php/issues/95

**Comment by btcdrak** [comment] 2015-06-25 17:11
I will close this then.

**Closed by btcdrak** 2015-06-25 17:11 UTC
